# Circle configuration to preview the opencontainers/org site as artifact

version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.0
    working_directory: ~/repo
    environment:
      - JEKYLL_ENV: production
      - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      - BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
          - rubygems-v2
      - run:
          name: Bundle Install
          command: |
              cd ~/repo
              bundle check || bundle install
      - save_cache:
          key: rubygems-v2
          paths:
            - vendor/bundle
      - run:
          name: Jekyll Build
          command: |              
              echo "Building Good Labs Site"
              mv ~/repo/.circleci/circle_urls.sh ~/repo/circle_urls.sh
              cd ~/repo
              chmod u+x circle_urls.sh
              bash circle_urls.sh              
              bundle exec jekyll build
      - store_artifacts:
          path: ~/repo/_site
          destination: good-labs.github.io

workflows:
  version: 2
  build-site:
    jobs:
      - build:
          filters:
            branches:
              ignore: ignore*
